import mongoose from 'mongoose';
export default new mongoose.Schema({
  jobTitle: String,
  datePosted: String,
  hiringOrganization: String,
  streetAddress: String,
  addressLocality: String,
  addressRegion: String,
  minCompValue: String,
  maxCompValue: String,
  compTimeUnit: String,
  workHours: String,
  specialCommitments: String,
  email: { type: String, required: true },
  jobPageId: { type: String, index: { unique: true } },
  employmentType: String,
  employmentSubType: String,
  startTime: String,
  benefits: String,
  vacancies: Number,
  verified: Boolean,
  validThrough: { type: Date, required: true },
  description: String,
  site1: Boolean,
  site2: Boolean,
  site3: Boolean,
  site4: Boolean,
  sent: Boolean,
});
